### ISSUE TITLE
Upgrade ember-cli-babel to eliminate deprecation warning

### ISSUE THREAD

**Issue by jacobq** [cibernox/ember-disable-proxy-controllers#4]
The current release (1.0.1) triggers a deprecation warning with recent versions of Ember (e.g. 2.18) that would be fixed by upgrading to the latest release of `ember-cli-babel` (from 5.x to 6.x). Please consider upgrading [this](https://github.com/cibernox/ember-disable-proxy-controllers/blob/master/package.json#L44).

```
├─┬ ember-disable-proxy-controllers@1.0.1
│ └─┬ ember-cli-babel@5.2.4
│   └── ember-cli-version-checker@1.3.1 
```

The deprecation warning looks like this and is described [here](https://github.com/ember-cli/ember-cli-version-checker/issues/48):
```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/path/to/project/node_modules/ember-getowner-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)
```

**Comment by cibernox** [comment]
@jacobq What version of Ember are you using? This addon is not needed for the last 2 years, since 2.0 or 2.4. I'd suggest to just remove it completely.

**Comment by jacobq** [comment]
In this case it's used by an addon (https://github.com/mike-north/ember-materialize-shim/blob/master/package.json#L34), which I believe is supposed to support some pretty old versions, so I'm hesitant to propose removing it without understanding its effects. Since it's just in `devDependencies` does that mean that downstream consumers won't be impacted?

**Comment by cibernox** [comment]
@jacobq for what I can see, that addon only tests back to Ember 2.12 (https://github.com/mike-north/ember-materialize-shim/blob/master/config/ember-try.js) so I think it's safe.

**Comment by jacobq** [comment]
I was hoping for more than "think/feel" but thanks :) 
That addon is actually used in `ember-cli-materialize` which is [supposed to support all of 2.x](https://github.com/mike-north/ember-cli-materialize#which-version-do-i-use) but I guess if we're not testing it and no one is using it we may as well not consider it supported.
I was hoping for an answer like, `devDependencies` are not fetched by consumers so will not affect them.
