### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath

### ISSUE THREAD

**Issue by Alonski** [cibernox/ember-disable-proxy-controllers#5]
While trying to update an app that uses this addon to v3.0.0 I ran into this deprecation:
`An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:`

This needs to be fixed so that projects using this addon can upgrade to v3.0.0.

This should fix it:
Upgrade the version checker: ember-cli/ember-cli-version-checker#48

**Comment by cibernox** [comment]
@Alonski proxy-controllers are not even in ember since 2.4 iirc, which was released over 2 years ago. If you are in Ember 3.0, you don't need this addon at all.

**Comment by Alonski** [comment]
@cibernox You sure do answer fast 😄 
All right I will remove it from the project I am updating: https://github.com/ember-learn/ember-api-docs/pull/470

Maybe it is possible to release a new version of this with a deprecation warning?

Thanks man, always a pleasure 👍
