### ISSUE TITLE
Update to new import syntax breaks Ember apps using older versions of ember-cli-babel

### ISSUE THREAD

**Issue by kevinyuliawan** [cibernox/ember-disable-proxy-controllers#8]
Our production app's package.json specifies:
```
"ember-cli-babel": "^5.1.6", (resolves to 5.2.8)
"ember-disable-proxy-controllers": "^1.0.1" (resolves to 1.0.2)
```
Since 1.0.2 now uses `import Controller from '@ember/controller'` syntax, this breaks our app with 

```
Ember.onerror stack: Error: Could not find module `@ember/controller` imported from `my-app/controllers/object`
```

Perhaps instead of being versioned to 1.0.2 it should be 2.0 since this is a breaking change for older Babel installations, and this plugin is meant for older versions of Ember anyway? 

For now, to fix our app we have specified our package.json to say:

```
"ember-disable-proxy-controllers": "1.0.1"
```
But it was still a tricky bug to track down.

**Comment by cibernox** [comment]
Good to know. I didn't realize that updating to the new imports could be breaking in ancient versions of babel 😞

**Comment by cibernox** [comment]
I think that reverting this now would cause more troubles than anything else, so I don't think that I can do much other than apologise for the trouble 🙇
